kubeadmconfig:
  files:
  - content: '[Unit]

      Description=Fence resources slice for Kubernetes services

      Documentation=man:systemd.special(7)

      DefaultDependencies=no

      Before=slices.target

      Requires=-.slice

      After=-.slice

      [Service]

      CPUAccounting=true'
    targetOwner: root:root
    targetPath: /etc/systemd/system/kube.slice
    targetPermissions: '0644'
  - content: '[Service]

      Slice=kube.slice'
    targetOwner: root:root
    targetPath: /etc/systemd/system/containerd.service.d/10-cgroup.conf
    targetPermissions: '0644'
  - content: '[Service]

      CPUAccounting=true

      MemoryAccounting=true

      Slice=kube.slice'
    targetOwner: root:root
    targetPath: /etc/systemd/system/kubelet.service.d/10-cgroup.conf
    targetPermissions: '0644'
  - content: 'blacklist nouveau

      blacklist lbm-nouveau

      options nouveau modeset=0

      alias nouveau off

      alias lbm-nouveau off'
    targetOwner: root:root
    targetPath: /etc/modprobe.d/blacklist-nouveau.conf
    targetPermissions: '0644'
  - content: '[Service]

      # allow children (shims/containers) to inherit unlimited memlock

      LimitMEMLOCK=infinity

      # (optional but common in HPC)

      LimitNOFILE=1048576

      LimitNPROC=infinity'
    targetOwner: root:root
    targetPath: /etc/systemd/system/containerd.service.d/override.conf
    targetPermissions: '0644'
  - content: "apiVersion: kubelet.config.k8s.io/v1beta1\nkind: KubeletConfiguration\nmaxPods: 250\nkubeReserved:\n  memory: 1Gi\n  ephemeral-storage: 5Gi\nsystemReserved:\n  memory: 1Gi\n  ephemeral-storage: 5Gi"
    targetOwner: root:root
    targetPath: /etc/kubernetes/kubelet.conf.d/10-kubelet-tuning.conf
    targetPermissions: '0644'
  postKubeadmCommands:
  - echo "====> Applying post Kubeadm commands"
  preKubeadmCommands:
  - echo "====> Applying pre Kubeadm commands"
  - "apt update && apt install -y grepcidr\nNETWORKS=\"{{ .spectro.var.K8sNodeCIDR }}\"\nIPS=$(hostname -I)\nfor IP in $IPS\ndo\n  echo \"$IP\" | grepcidr \"$NETWORKS\" >/dev/null && echo \" --node-ip=$IP\" >> /etc/default/kubelet\n  if [ $? -eq 0 ]; then break; fi\ndone\n"
  - apt install -y nfs-common
  - update-ca-certificates
  - update-initramfs -u
  - sed -i '/# contains spectro changes/Q' /etc/containerd/config.toml
  - systemctl daemon-reload
  - systemctl restart containerd
  - 'apt-mark hold $(apt-mark showauto linux-\*image-\*)

    apt-mark hold $(apt-mark showauto linux-\*headers-\*)

    apt-mark hold $(apt-mark showauto linux-\*modules-\*)

    apt-mark hold $(apt-mark showauto linux-\*cloud-tools-\*)

    apt-mark hold $(apt-mark showauto linux-\*tools-\*)

    apt-mark hold $(apt-mark showmanual linux-\*image-\*)

    apt-mark hold $(apt-mark showmanual linux-\*headers-\*)

    apt-mark hold $(apt-mark showmanual linux-\*modules-\*)

    apt-mark hold $(apt-mark showmanual linux-\*cloud-tools-\*)

    apt-mark hold $(apt-mark showmanual linux-\*tools-\*)

    '
  - "systemctl daemon-reload\nsystemctl restart containerd kubelet\n"
